config/routes.rb
Rails.application.routes.draw do
  resources :expenses

  resources :categories

  root 'expenses#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :expenses
	validates :name, presence: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to expenses_path(format: :html), notice: 'Category was successfully created.' }
        #format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        #format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:fecha, :concept, :amount, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Nueva Categoría" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

<%= link_to 'Volver a gastos', expenses_path(format: :html) %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :Concepto %><br>
    <%= f.text_area :concept %>
  </div>
  <div class="field">
    <%= f.label :Monto %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :Categoria %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %><br>
    <%= link_to 'Crear categoría', new_category_path(format: :html) %><br>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Edición</h1>

<%= render 'form' %>

<%= link_to 'Ver', @expense %> |
<%= link_to 'Atrás', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mis Finanzas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Concepto</th>
      <th>Monto</th>
      <th>Categoría</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.fecha %></td>
        <td><%= expense.concept %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.category.name %></td>
        <td><%= link_to 'Ver', expense %></td>
        <td><%= link_to 'Editar', edit_expense_path(expense) %></td>
        <td><%= link_to 'Eliminar', expense, method: :delete, data: { confirm: 'No se puede deshacer esta acción, ¿Está usted seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo gasto', new_expense_path %>

app/views/expenses/new.html.erb
<h1>Nuevo</h1>

<%= render 'form' %>

<%= link_to 'Atrás', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @expense.fecha %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @expense.concept %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @expense.category.name %>
</p>

<%= link_to 'Editar', edit_expense_path(@expense) %> |
<%= link_to 'Atrás', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mis gastos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px;">
	<div id="main-container" class="container">
		<div class="row">
			<div class="col-xs-9">
				<nav class="navbar navbar-default navbar-fixed-top">
	  				<div class="container-fluid">
					    <div class="navbar-header">
      						<a class="navbar-brand" href="/expenses">
        						MIS<strong>GASTOS</strong>
      						</a>
    					</div>
  	  				</div>
				</nav>
				<%= yield %>
			</div>
			<div class="col-xs-3">
				<div class="btn-group-vertical" role="group">
  					
				</div>
			</div>
		</div>
	</div>
</body>
</html>